import mermaid from 'mermaid'
import DOMPurify from 'dompurify'

// Running counter for unique mermaid render IDs within a session. A simple
// counter is used rather than a content hash because Mermaid's cache is reset
// before each render pass anyway (see below).
let diagramCounter = 0

export function initMermaid(theme: 'default' | 'dark'): void {
  mermaid.initialize({
    // WHY startOnLoad: false — we control when diagrams render (after the HTML
    // is injected into the DOM), not on DOMContentLoaded.
    startOnLoad: false,
    theme,
    // WHY securityLevel 'loose' — Mermaid's default 'strict' mode wraps output
    // in an iframe which prevents CSS theming and breaks layout. 'loose' outputs
    // inline SVG. The SVG is sanitized with DOMPurify (SVG profile) immediately
    // after render before being written to the DOM.
    securityLevel: 'loose',
  })
}

export async function renderMermaidBlocks(container: HTMLElement): Promise<void> {
  const blocks = Array.from(
    container.querySelectorAll<HTMLElement>('pre.mermaid-source'),
  )

  if (blocks.length === 0) return

  // The incrementing diagramCounter guarantees a unique ID for every render
  // call, so Mermaid never serves a stale cached SVG for a new render pass.
  // mermaidAPI.reset() (a private internal API) is intentionally NOT called —
  // unique IDs make it redundant, and private APIs can break across versions.

  for (const pre of blocks) {
    const source = pre.querySelector('code')?.textContent ?? ''

    // WHY 'mermaid-' prefix: prevents collision with heading anchor id values
    // generated by remark-rehype (see ADR-004).
    const id = `mermaid-${diagramCounter++}`

    try {
      const { svg } = await mermaid.render(id, source)

      // Sanitize the SVG with DOMPurify's SVG profile before DOM insertion.
      // securityLevel:'loose' outputs inline SVG that may contain <script> or
      // event-handler attributes from a malicious diagram source.
      const cleanSvg = DOMPurify.sanitize(svg, {
        USE_PROFILES: { svg: true, svgFilters: true },
      })

      const figure = document.createElement('figure')
      figure.className = 'mermaid-diagram'
      figure.setAttribute('role', 'img')
      figure.setAttribute('aria-label', 'Mermaid diagram')
      figure.innerHTML = cleanSvg

      pre.replaceWith(figure)
    } catch (err: unknown) {
      const message =
        err instanceof Error
          ? err.message
          : typeof err === 'object' && err !== null && 'str' in err
            ? String((err as { str: unknown }).str)
            : String(err)

      const errorDiv = document.createElement('div')
      errorDiv.className = 'mermaid-error'

      const msgP = document.createElement('p')
      msgP.className = 'mermaid-error__message'
      msgP.textContent = message

      const code = document.createElement('code')
      code.textContent = source
      const sourcePre = document.createElement('pre')
      sourcePre.className = 'mermaid-error__source'
      sourcePre.appendChild(code)

      errorDiv.appendChild(msgP)
      errorDiv.appendChild(sourcePre)
      pre.replaceWith(errorDiv)
    }
  }
}
