import mermaid from 'mermaid'

// Running counter for unique mermaid render IDs within a session. A simple
// counter is used rather than a content hash because Mermaid's cache is reset
// before each render pass anyway (see below).
let diagramCounter = 0

export function initMermaid(theme: 'default' | 'dark'): void {
  mermaid.initialize({
    // WHY startOnLoad: false — we control when diagrams render (after the HTML
    // is injected into the DOM), not on DOMContentLoaded.
    startOnLoad: false,
    theme,
    // WHY securityLevel 'loose' — Mermaid's default 'strict' mode wraps output
    // in an iframe which prevents CSS theming and breaks layout. 'loose' outputs
    // inline SVG. The SVG is sanitized immediately after render before DOM insertion.
    securityLevel: 'loose',
  })
}

// WHY a custom DOM sanitizer instead of DOMPurify:
// Mermaid v11 renders node labels as <foreignObject><div><span><p> inside the
// SVG. DOMPurify's namespace validation removes HTML-namespace elements
// (div/span/p) that are children of SVG-namespace foreignObject, regardless of
// ADD_TAGS or ADD_ATTR options — this leaves every node box empty. A DOM-based
// walk avoids all namespace-check stripping: we parse once via innerHTML (which
// correctly switches to HTML-content mode inside foreignObject per the HTML5
// spec), then remove only the actual threats in-place before appending.
function sanitizeSvgFragment(svgString: string): DocumentFragment {
  const tmp = document.createElement('div')
  tmp.innerHTML = svgString

  // Remove script elements entirely.
  for (const el of Array.from(tmp.querySelectorAll('script'))) el.remove()

  // Strip event-handler attributes (on*), javascript: URLs, and data: URIs
  // that could execute script. Mermaid v11 (securityLevel:'loose') renders
  // node labels as HTML inside foreignObject — a crafted label could inject
  // <a href="data:text/html,..."> that survives without this check.
  const DANGEROUS_URL = /^(?:javascript:|data:(?!image\/))/i
  for (const el of Array.from(tmp.querySelectorAll('*'))) {
    for (const attr of Array.from(el.attributes)) {
      const val = attr.value.trimStart()
      if (
        /^on\w/i.test(attr.name) ||
        DANGEROUS_URL.test(val)
      ) {
        el.removeAttribute(attr.name)
      }
    }
  }

  const frag = document.createDocumentFragment()
  while (tmp.firstChild) frag.appendChild(tmp.firstChild)
  return frag
}

// Re-renders every already-rendered mermaid figure in `container` using the
// current mermaid theme (set via the most recent initMermaid call). Called on
// OS theme change instead of reloading the entire file, so scroll position is
// preserved and only the SVGs update.
export async function rerenderMermaidTheme(container: HTMLElement): Promise<void> {
  const figures = Array.from(
    container.querySelectorAll<HTMLElement>('figure.mermaid-diagram[data-mermaid-src]'),
  )

  for (const figure of figures) {
    const source = figure.dataset.mermaidSrc ?? ''
    const id = `mermaid-${diagramCounter++}`

    try {
      const { svg } = await mermaid.render(id, source)
      const cleanFragment = sanitizeSvgFragment(svg)

      if (!cleanFragment.firstChild) continue

      figure.replaceChildren(cleanFragment)
    } catch {
      // Leave the existing diagram in place rather than replacing with an
      // error on a theme change — the diagram was valid when first rendered.
    }
  }
}

export async function renderMermaidBlocks(container: HTMLElement): Promise<void> {
  const blocks = Array.from(
    container.querySelectorAll<HTMLElement>('pre.mermaid-source'),
  )

  if (blocks.length === 0) return

  // The incrementing diagramCounter guarantees a unique ID for every render
  // call, so Mermaid never serves a stale cached SVG for a new render pass.
  // mermaidAPI.reset() (a private internal API) is intentionally NOT called —
  // unique IDs make it redundant, and private APIs can break across versions.

  for (const pre of blocks) {
    const source = pre.querySelector('code')?.textContent ?? ''

    // WHY 'mermaid-' prefix: prevents collision with heading anchor id values
    // generated by remark-rehype (see architecture.md#diagram-renderer-mermaidjs).
    const id = `mermaid-${diagramCounter++}`

    try {
      const { svg } = await mermaid.render(id, source)

      const cleanFragment = sanitizeSvgFragment(svg)

      if (!cleanFragment.firstChild) {
        throw new Error('SVG was empty after sanitization — diagram may use unsupported elements')
      }

      const figure = document.createElement('figure')
      figure.className = 'mermaid-diagram'
      figure.setAttribute('role', 'img')
      figure.setAttribute('aria-label', 'Mermaid diagram')
      // Store the source so re-theming can re-render figures in-place without
      // a full file reload (see rerenderMermaidTheme below).
      figure.dataset.mermaidSrc = source
      figure.appendChild(cleanFragment)

      pre.replaceWith(figure)
    } catch (err: unknown) {
      const message =
        err instanceof Error
          ? err.message
          : typeof err === 'object' && err !== null && 'str' in err
            ? String((err as { str: unknown }).str)
            : String(err)

      console.error('[mermaid] render failed:', message, '\nsource:', source)

      // TODO: render the error message as visible inline text and include the
      // raw source in a scrollable <code> block below it. Currently the message
      // is only in the title tooltip. See docs/unimplemented.md#mermaid-error-display.
      const broken = document.createElement('figure')
      broken.className = 'mermaid-broken'
      broken.title = message
      pre.replaceWith(broken)
    }
  }
}
